language: node_js # 设置语言

node_js: stable # 设置相应版本

install: 
    - npm install # 安装 hexo及插件

script: 
    - hexo clean # 清除hexo缓存
    - hexo g # 通过 markdown 源码 生成 html

after_script: 
    - cd ./public
    - git init
    - git config user.name "autositestart" # 修改name
    - git config user.email "autostart@protonmail.com" # 修改email
    - git add .
    - git commit . -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${Travis_Token}@${HOST}" master:master # Travis_Token 是travis环境变量里配置的

branches: 
    only: 
        - hexo # 只监测 hexo 分支

env: 
    global: 
        - HOST: github.com/autositestart/autositestart.github.io.git # 设置仓库地址

